services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch_8.13.0
    environment:
      - ELASTIC_PASSWORD=admin
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms3g -Xmx3g
      - discovery.type=single-node
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -s http://localhost:9200/_cluster/health | grep -q ''status":"green''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - 8080:8080
    volumes:
      - searxng_config:/etc/searxng
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=MySearXNG
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD-SHELL', "curl -s http://localhost:8080/healthz | grep -q 'OK'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  elasticsearch_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/repositories/ai-playground/elastic_search_data
  searxng_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/repositories/ai-playground/searxng_config
