import React from 'react';

import { Button } from '@/components/ui/button';

import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';
import { Search } from 'lucide-react';
import Spinner from '@/app/components/spinner';
import { useChatWithDatabase } from '../context/chat-with-database-context';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
const ViewRAGSourcesDialog = ({
  disabled,
  isLoading,
}: {
  disabled: boolean;
  isLoading: boolean;
}) => {
  const { ragSources } = useChatWithDatabase();

  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button
          type='button'
          variant='ghost'
          disabled={isLoading || disabled}
          className='text-blue-500 '
        >
          {!isLoading && <Search />}
          <Spinner isLoading={isLoading} />
          View Sources
        </Button>
      </SheetTrigger>
      <SheetContent className=' p-4 min-w-[500px]'>
        <SheetHeader>
          <SheetTitle>Sources of the Response</SheetTitle>
          <SheetDescription>
            Below are the sources of the response generated by the model.
          </SheetDescription>
        </SheetHeader>
        <div className='flex h-full flex-col mt-4  w-full  overflow-y-auto'>
          {ragSources.map((source, index) => (
            <div key={index} className='mb-4'>
              {/* Added margin-bottom for spacing */}
              <div className='bg-white rounded-md shadow-md border-2 w-full'>
                <h3 className='text-lg bg-slate-100 font-semibold border-b '>
                  <span className='p-2'>Source {index + 1}</span>
                </h3>
                <div className='prose p-2 break-words whitespace-pre-line'>
                  <Markdown remarkPlugins={[remarkGfm]}>{source}</Markdown>
                </div>
              </div>
            </div>
          ))}
        </div>
        <SheetFooter>
          <SheetClose asChild>
            <Button type='submit'>Save changes</Button>
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
};

export default ViewRAGSourcesDialog;
